### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by KerryRitter** [scf4/lyricist#6]
I am currently getting this error:

ReferenceError: regeneratorRuntime is not defined
    at C:\Workspaces\setlister\scraper-api\node_modules\lyricist\dist\index.js:38:36
    at C:\Workspaces\setlister\scraper-api\node_modules\lyricist\dist\index.js:77:6
    at Object.<anonymous> (C:\Workspaces\setlister\scraper-api\node_modules\lyricist\dist\index.js:414:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

I'm on Node 6.10.2. What are the other steps?

**Comment by scf4** [comment]
Upgrading to 2.1.1 and requiring 'lyricist/node6' should fix this error
